// Code generated by goctl. DO NOT EDIT!
// Source: transform.proto

package server

import (
	"context"

	"github.com/realjf/go-zero-demo/service/user/rpc/transform/internal/logic"
	"github.com/realjf/go-zero-demo/service/user/rpc/transform/internal/svc"
	"github.com/realjf/go-zero-demo/service/user/rpc/transform/transform"
)

type TransformerServer struct {
	svcCtx *svc.ServiceContext
	transform.UnimplementedTransformerServer
}

func NewTransformerServer(svcCtx *svc.ServiceContext) *TransformerServer {
	return &TransformerServer{
		svcCtx: svcCtx,
	}
}

func (s *TransformerServer) Login(ctx context.Context, in *transform.LoginReq) (*transform.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *TransformerServer) Register(ctx context.Context, in *transform.RegisterReq) (*transform.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *TransformerServer) GetUser(ctx context.Context, in *transform.UserInfoReq) (*transform.UserInfoResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
