// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserInfoReq struct {
}

type LoginResp struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	AccessToken  string `json:"token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type RegisterResp struct {
}

type UserInfoResp struct {
	Uid      int64  `json:"uid"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
